### PR TITLE
Fixed error where if you reloaded the page, user assessments wouldn't…

### PR DESCRIPTION
**Pull request by jdhang**
… load. Also corrected the solution path error to disappear after a correct file path addition.

### CODE REVIEW

**Comment by jes708** [comment]
coo 😎

**Comment by jdhang** [comment]
i'll fix these!

**Comment by jes708** [comment]
❕ ❗ ❕ ❗ ❕ ❗ ❕ ❗ ❕ ❗ ❕ ❗ ❕ ❗

**Comment by jdhang** [comment]
:shipit: ??!?!?!?

**Pull request merged**
